name: Releaser
on:
  push:
    tags:
      - "*"
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions: write-all
    name: Create GH Release
    steps:
      - uses: actions/checkout@v3
      - name: Build Artifacts
        run: ./release.sh
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} aws_ebook_downloader_chrome.zip aws_ebook_downloader_firefox.zip --generate-notes
